INSERT INTO product(category, sub_category, producer_name, name, description, img) VALUES
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel 1', 'Laptop 1', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel', 'Laptop 2', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel 2', 'Laptop 3', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel', 'Laptop 4', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel 2', 'Laptop 5', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'Laptops', 'Ovonel', 'Laptop 6', 'New fast laptop from the best producer!', NULL),
                                                                                             ('Laptops & PCs', 'PCs', 'Pc maker', 'Pc 1', 'Pc with the best components!', NULL),
                                                                                             ('Laptops & PCs', 'PCs', 'Pc maker1', 'Pc 2', 'Pc with the best components!', NULL),
                                                                                             ('Laptops & PCs', 'PCs', 'Pc maker', 'Pc 3', 'Pc with the best components!', NULL),
                                                                                             ('Laptops & PCs', 'PCs', 'Pc maker2', 'Pc 4', 'Pc with the best components!', NULL),
                                                                                             ('Laptops & PCs', 'PCs', 'Pc maker', 'Pc 5', 'Pc with the best components!', NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik', 'Ebook reader 1', 'The best ebook reader in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik 1', 'Ebook reader 2', 'The best ebook reader in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik', 'Ebook reader 3', 'The best ebook reader in the world!',NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik', 'Ebook reader 4', 'The best ebook reader in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik 2', 'Ebook reader 5', 'The best ebook reader in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Ebook readers', 'Eldnik', 'Ebook reader 6', 'The best ebook reader in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop', 'Smartphone 1', 'The best smartphone in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop 1', 'Smartphone 2', 'The best smartphone in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop', 'Smartphone 3', 'The best smartphone in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop', 'Smartphone 4', 'The best smartphone in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop 2', 'Smartphone 5', 'The best smartphone in the world!', NULL),
                                                                                             ('Smartphones & Readers', 'Smartphones', 'Ocop', 'Smartphone 6', 'The best smartphone in the world!', NULL),
                                                                                             ('Gaming & streaming', 'Gaming PC', 'Rezar', 'Gaming pc 1', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Gaming & streaming', 'Gaming PC', 'Rezar 1', 'Gaming pc 2', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Gaming & streaming', 'Gaming PC', 'Rezar', 'Gaming pc 3', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Gaming & streaming', 'Gaming PC', 'Rezar 2', 'Gaming pc 4', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Gaming & streaming', 'Gaming PC', 'Rezar', 'Gaming pc 5', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel', 'Gaming laptop 1', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel', 'Gaming laptop 2', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel 1', 'Gaming laptop 3', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel', 'Gaming laptop 4', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel 1', 'Gaming laptop 5', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel', 'Gaming laptop 6', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Gaming & streaming', 'Gaming laptops', 'Ovonel', 'Gaming laptop 7', 'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Computer components', 'Hard discs', 'DW Disc', 'HDD 1', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Computer components', 'Hard discs', 'DW Disc', 'HDD 2', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Computer components', 'Hard discs', 'DWD Disc', 'HDD 3', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Computer components', 'Hard discs', 'DW Disc', 'HDD 4', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Computer components', 'Hard discs', 'DWD Disc', 'HDD 5', 'Lorem ipsum dolor sit amet', NULL),
                                                                                             ('Computer components', 'Procesors', 'Letni', 'Processor 1', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Computer components', 'Procesors', 'Letni', 'Processor 2', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Computer components', 'Procesors', 'Letni', 'Processor 3', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Computer components', 'Procesors', 'Letni 1', 'Processor 4', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('Computer components', 'Procesors', 'Letni', 'Processor 5', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Monitors', 'CEN', 'Monitor 1', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Monitors', 'CEN', 'Monitor 2', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Monitors', 'CEN', 'Monitor 3', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Monitors', 'CEN', 'Monitor 4', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Monitors', 'CEN 1', 'Monitor 5', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED', 'Keyboard 1', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED', 'Keyboard 2', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED', 'Keyboard 3', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED', 'Keyboard 4', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED 1', 'Keyboard 5', 'Libero ipsum fringilla leo, non congue mi.', NULL),
                                                                                             ('off-line equipments', 'Keyboards', 'LLED', 'Keyboard 6', 'Libero ipsum fringilla leo, non congue mi.', NULL);

INSERT INTO address(address, city, country, postal_code, additional_info) VALUES
                                                                              ('Poznanska 15', 'Gniezno', 'Poland', '62-200', NULL),
                                                                              ('Poznanska 25', 'Krakow', 'Poland', '30-409', NULL),
                                                                              ('Krakowska 16', 'Pcim', 'Poland', '60-201', NULL);

INSERT INTO seller(id_address, seller_name, description, email, login, password, is_active) VALUES
                                                                                                (1, 'Ecommorce Main Shop', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut euismod ipsum.', 'email@mail.com', 'Ecommerce', 'Password', 1),
                                                                                                (2, 'Ecommorce Second Shop', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut euismod ipsum.', 'email1@mail.com', 'Ecommerce1', 'Password1', 1);

INSERT INTO seller_products(id_seller, id_product, quantity, price_gross_per_item, price_net_per_item) VALUES
                                                                                                           (1, 1, 10, 450.00, 480.35),
                                                                                                           (1, 2, 10, 460.00, 490.35);