INSERT INTO product(category, producer_name, name, description, img, price_net, price_gross, available)
VALUES ('Laptops & PCs', 'Ovonel 1', 'Laptop 1', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop1.jpg', 1000.00, 1230.00, true),
       ('Laptops & PCs', 'Ovonel', 'Laptop 2', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop2.jpg', 1500.00, 1845.00, true),
       ('Laptops & PCs', 'Ovonel 2', 'Laptop 3', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop2.jpg', 1000.00, 1230.00, true),
       ('Laptops & PCs', 'Ovonel', 'Laptop 4', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop1.jpg', 1500.00, 1845.00, true),
       ('Laptops & PCs', 'Ovonel 2', 'Laptop 5', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop2.jpg', 2000.00, 2460.00, true),
       ('Laptops & PCs', 'Ovonel', 'Laptop 6', 'New fast laptop from the best producer!',
        'http://localhost:8080/api/v1/image/laptop1.jpg', 2000.00, 2460.00, true),
       ('Laptops & PCs', 'Pc maker', 'Pc 1', 'Pc with the best components!',
        'http://localhost:8080/api/v1/image/pc1.jpg', 1500.00, 1845.00, true),
       ('Laptops & PCs', 'Pc maker1', 'Pc 2', 'Pc with the best components!',
        'http://localhost:8080/api/v1/image/pc2.jpg', 1000.00, 1230.00, true),
       ('Laptops & PCs', 'Pc maker', 'Pc 3', 'Pc with the best components!',
        'http://localhost:8080/api/v1/image/pc1.jpg', 1500.00, 1845.00, true),
       ('Laptops & PCs', 'Pc maker2', 'Pc 4', 'Pc with the best components!',
        'http://localhost:8080/api/v1/image/pc2.jpg', 2000.00, 2460.00, true),
       ('Laptops & PCs', 'Pc maker', 'Pc 5', 'Pc with the best components!',
        'http://localhost:8080/api/v1/image/pc1.jpg', 1500.00, 1845.00, true),
       ('Smartphones & Readers', 'Eldnik', 'Ebook reader 1', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader1.jpg', 800.00, 984.00, true),
       ('Smartphones & Readers', 'Eldnik 1', 'Ebook reader 2', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader2.jpg', 1000.00, 1230.00, true),
       ('Smartphones & Readers', 'Eldnik', 'Ebook reader 3', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader1.jpg', 700.00, 861.00, true),
       ('Smartphones & Readers', 'Eldnik', 'Ebook reader 4', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader2.jpg', 800.00, 984.00, true),
       ('Smartphones & Readers', 'Eldnik 2', 'Ebook reader 5', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader2.jpg', 1000.00, 1230.00, true),
       ('Smartphones & Readers', 'Eldnik', 'Ebook reader 6', 'The best ebook reader in the world!',
        'http://localhost:8080/api/v1/image/ebookreader1.jpg', 800.00, 984.00, true),
       ('Smartphones & Readers', 'Ocop', 'Smartphone 1', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone1.jpg', 700.00, 861.00, true),
       ('Smartphones & Readers', 'Ocop 1', 'Smartphone 2', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone2.jpg', 800.00, 984.00, true),
       ('Smartphones & Readers', 'Ocop', 'Smartphone 3', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone1.jpg', 1000.00, 1230.00, true),
       ('Smartphones & Readers', 'Ocop', 'Smartphone 4', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone1.jpg', 800.00, 984.00, true),
       ('Smartphones & Readers', 'Ocop 2', 'Smartphone 5', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone2.jpg', 700.00, 861.00, true),
       ('Smartphones & Readers', 'Ocop', 'Smartphone 6', 'The best smartphone in the world!',
        'http://localhost:8080/api/v1/image/smartphone1.jpg', 1000.00, 1230.00, true),
       ('Printers & Ink', 'PH', 'Printer 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/printer1.jpg', 700.00, 861.00, true),
       ('Printers & Ink', 'Nonac', 'Printer 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/printer1.jpg', 800.00, 984.00, true),
       ('Printers & Ink', 'PH', 'Printer 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/printer1.jpg', 1000.00, 1230.00, true),
       ('Printers & Ink', 'Nonac', 'Printer 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/printer1.jpg', 800.00, 984.00, true),
       ('Printers & Ink', 'Nospe', 'Printer 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/printer1.jpg', 1000.00, 1230.00, true),
       ('Printers & Ink', 'Ovonel', 'Ink black 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 50.00, 61.50, true),
       ('Printers & Ink', 'Nonac', 'Ink blue 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 40.00, 49.20, true),
       ('Printers & Ink', 'PH', 'Ink yellow 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 35.00, 43.05, true),
       ('Printers & Ink', 'Kni', 'Ink red 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 50.00, 61.50, true),
       ('Printers & Ink', 'Ink producer', 'Ink black 2',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 40.00, 49.20, true),
       ('Printers & Ink', 'Kni', 'Ink black 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 50.00, 61.50, true),
       ('Printers & Ink', 'Kni', 'Ink black 1',
        'Sed luctus, leo vel fringilla volutpat, libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/ink1.jpg', 50.00, 61.50, true),
       ('Computer components', 'DW Disc', 'HDD 1', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/harddisk2.jpg', 100.00, 123.00, true),
       ('Computer components', 'DW Disc', 'HDD 2', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/harddisk1.jpg', 200.00, 246.00, true),
       ('Computer components', 'DWD Disc', 'HDD 3', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/harddisk2.jpg', 100.00, 123.00, true),
       ('Computer components', 'DW Disc', 'HDD 4', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/harddisk1.jpg', 200.00, 245.00, true),
       ('Computer components', 'DWD Disc', 'HDD 5', 'Lorem ipsum dolor sit amet',
        'http://localhost:8080/api/v1/image/harddisk2.jpg', 100.00, 123.00, true),
       ('Computer components', 'Letni', 'Processor 1', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/processor1.jpg', 200.00, 246.00, true),
       ('Computer components', 'Letni', 'Processor 2', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/processor2.jpg', 750.00, 922.50, true),
       ('Computer components', 'DMA', 'Processor 3', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/processor1.jpg', 200.00, 246.00, true),
       ('Computer components', 'Letni 1', 'Processor 4', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/processor2.jpg', 750.00, 922.50, true),
       ('Computer components', 'ITA', 'Processor 5', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/processor1.jpg', 200.00, 246.00, true),
       ('Computer Accessories', 'CEN', 'Monitor 1', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/monitor1.jpg', 500.00, 615.00, true),
       ('Computer Accessories', 'CEN', 'Monitor 2', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/monitor2.jpg', 700.00, 861.00, true),
       ('Computer Accessories', 'CEN', 'Monitor 3', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/monitor1.jpg', 500.00, 615.00, true),
       ('Computer Accessories', 'CEN', 'Monitor 4', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/monitor2.jpg', 500.00, 615.00, true),
       ('Computer Accessories', 'CEN 1', 'Monitor 5', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/monitor1.jpg', 700.00, 861.00, true),
       ('Computer Accessories', 'LLED', 'Keyboard 1', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard1.jpg', 50.00, 61.50, true),
       ('Computer Accessories', 'LLED', 'Keyboard 2', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard2.jpg', 500.00, 615.00, true),
       ('Computer Accessories', 'LLED', 'Keyboard 3', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard1.jpg', 100.00, 123.00, true),
       ('Computer Accessories', 'LLED', 'Keyboard 4', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard2.jpg', 50.00, 61.50, true),
       ('Computer Accessories', 'LLED 1', 'Keyboard 5', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard1.jpg', 100.00, 123.00, true),
       ('Computer Accessories', 'LLED', 'Keyboard 6', 'Libero ipsum fringilla leo, non congue mi.',
        'http://localhost:8080/api/v1/image/keyboard2.jpg', 50.00, 61.50, true);

INSERT INTO address(address, city, country, postal_code)
VALUES ('Poznanska 15', 'Gniezno', 'Poland', '62-200'),
       ('Poznanska 25', 'Krakow', 'Poland', '30-409'),
       ('Krakowska 16', 'Pcim', 'Poland', '60-201');

INSERT INTO user(email, login, password, name, last_name, role, enabled)
VALUES ('email@email.com', 'user1', '$2a$10$J17Tl4lsfCZeyLQbN4xa/e2oGzNdTUy.dyzWs6/ESUpsV7TmqVnLG', 'John', 'Whick',
        'user', TRUE),
       ('email@email.com', 'user2', '$2a$10$.4di3DlpJbEWjU7j9.mlgekjekmUkGkBUISSNObZwe9YkxZa1cju.', 'Bob', 'Byte',
        'user', TRUE),
       ('email@email.com', 'user3', '$2a$10$dXRPMwnGSuNsea6.KHWBKuPQLs1s7odLQvqJXRVFvEyE/qDHyvc5i', 'Alice', 'Bit',
        'user', TRUE),
       ('email@email.com', 'admin', '$2a$10$B74YiQiY0AsJ7lmm/wGeS.0bDUG9V3/l/KuT9uEZS1H2JCwDZs45y', 'Super', 'User',
        'admin', TRUE);

INSERT INTO user_addresses(user_id, addresses_id)
VALUES (1, 1),
       (1, 2),
       (2, 3);

INSERT INTO cart(total_items, total_price_gross, total_price_net)
VALUES (5, 1000, 1230);

INSERT INTO cart_item(amount, product_id)
VALUES (5, 1);

INSERT INTO cart_products(cart_id, products_id)
VALUES (1, 1);

INSERT INTO user(email, login, password, name, last_name, role, enabled, cart_id)
VALUES ('email@email.com', 'testing', '$2a$10$J17Tl4lsfCZeyLQbN4xa/e2oGzNdTUy.dyzWs6/ESUpsV7TmqVnLG', 'John', 'Whick',
        'user', TRUE, 1);

INSERT INTO stock(product_id, amount, updated_date)
VALUES (1, 10, CURRENT_DATE),
       (2, 4, CURRENT_DATE),
       (3, 5, CURRENT_DATE),
       (4, 12, CURRENT_DATE),
       (5, 14, CURRENT_DATE),
       (6, 10, CURRENT_DATE),
       (7, 3, CURRENT_DATE),
       (8, 2, CURRENT_DATE),
       (9, 0, CURRENT_DATE),
       (10, 2, CURRENT_DATE),
       (11, 0, CURRENT_DATE),
       (12, 5, CURRENT_DATE),
       (13, 3, CURRENT_DATE),
       (14, 6, CURRENT_DATE),
       (15, 7, CURRENT_DATE),
       (16, 0, CURRENT_DATE),
       (17, 5, CURRENT_DATE),
       (18, 12, CURRENT_DATE),
       (19, 14, CURRENT_DATE),
       (20, 2, CURRENT_DATE),
       (21, 12, CURRENT_DATE),
       (22, 4, CURRENT_DATE),
       (23, 15, CURRENT_DATE),
       (24, 6, CURRENT_DATE),
       (25, 0, CURRENT_DATE),
       (26, 1, CURRENT_DATE),
       (27, 12, CURRENT_DATE),
       (28, 1, CURRENT_DATE),
       (29, 0, CURRENT_DATE),
       (30, 14, CURRENT_DATE),
       (31, 0, CURRENT_DATE),
       (32, 10, CURRENT_DATE),
       (33, 12, CURRENT_DATE),
       (34, 10, CURRENT_DATE),
       (35, 1, CURRENT_DATE),
       (36, 10, CURRENT_DATE),
       (37, 2, CURRENT_DATE),
       (38, 0, CURRENT_DATE),
       (39, 10, CURRENT_DATE),
       (40, 2, CURRENT_DATE),
       (41, 1, CURRENT_DATE),
       (42, 10, CURRENT_DATE),
       (43, 0, CURRENT_DATE),
       (44, 10, CURRENT_DATE),
       (45, 2, CURRENT_DATE),
       (46, 10, CURRENT_DATE),
       (47, 0, CURRENT_DATE),
       (48, 10, CURRENT_DATE),
       (49, 4, CURRENT_DATE),
       (50, 0, CURRENT_DATE),
       (51, 10, CURRENT_DATE),
       (52, 5, CURRENT_DATE),
       (53, 10, CURRENT_DATE),
       (54, 6, CURRENT_DATE),
       (55, 10, CURRENT_DATE),
       (56, 0, CURRENT_DATE);